// app/assets/ts/stats-card.component.ts
/**
 * Created by cristiand on 11/2/2016.
 */

import {Component, OnInit, Input} from "@angular/core";
import {HealthReport} from "./models";
import {HTML_TEMPLATE} from "./constants";

@Component({
    selector: 'stats-card',
    templateUrl: HTML_TEMPLATE + 'stats-card.component.html'
})

export class StatsCardComponent implements OnInit {

    color: string;
    @Input() healthReport: HealthReport;

    ngOnInit() {
        if (this.healthReport.score == 100) this.color = "green-text";
        else if (this.healthReport.score >= 80) this.color = "blue-text";
        else if (this.healthReport.score < 50) this.color = "red-text";
    }

}

// app/assets/javascripts/statsCard.jsx

/**
 * The content of the build card.
 */
var StatsCard = React.createClass({
    render() {
        var color = "";
        if (this.props.score  == 100) color = "green-text";
        if (this.props.score >= 80) color = "blue-text";
        if (this.props.score < 50) color = "red-text";

        return (
            <div>
                <span className="stats-score {color}">{this.props.score}</span>
                <span>{this.props.description}</span>
            </div>
        )
    }
});
